/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#eae1da",
        "primary-container": "#b15f00",
        "outline-variant": "#dbc2b0",
        "on-secondary-fixed": "#00210a",
        "on-surface-variant": "#554336",
        "on-background": "#1f1b17",
        "surface-container-low": "#fcf2eb",
        "background": "#fff8f5",
        "on-tertiary-fixed-variant": "#763300",
        "secondary-container": "#92f5a4",
        "on-primary-container": "#fffbff",
        "on-primary-fixed-variant": "#6e3900",
        "surface-bright": "#fff8f5",
        "inverse-on-surface": "#f9efe8",
        "secondary": "#006d30",
        "on-tertiary-container": "#fffbff",
        "secondary-fixed-dim": "#79db8d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#95f8a7",
        "surface-container-high": "#f0e6e0",
        "tertiary-container": "#bb5810",
        "surface": "#fff8f5",
        "outline": "#887364",
        "tertiary-fixed": "#ffdbca",
        "on-secondary-container": "#007233",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#eae1da",
        "tertiary": "#984300",
        "surface-dim": "#e2d8d2",
        "inverse-surface": "#342f2b",
        "on-surface": "#1f1b17",
        "primary-fixed-dim": "#ffb77d",
        "tertiary-fixed-dim": "#ffb68e",
        "surface-container": "#f6ece6",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#331200",
        "surface-tint": "#904d00",
        "error-container": "#ffdad6",
        "primary": "#8d4b00",
        "primary-fixed": "#ffdcc3",
        "error": "#ba1a1a",
        "inverse-primary": "#ffb77d",
        "on-error": "#ffffff",
        "on-primary-fixed": "#2f1500",
        "on-secondary-fixed-variant": "#005323"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-screen": "1.25rem",
        "pad-md": "1rem",
        "pad-2xl": "3rem",
        "touch-min": "4rem",
        "gap-grid": "1rem",
        "pad-xl": "2rem",
        "pad-lg": "1.5rem",
        "pad-sm": "0.75rem",
        "touch-compact": "3.5rem",
        "pad-xs": "0.5rem"
      },
      fontFamily: {
        "body-sm": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
