import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'hi', label: 'हिन्दी', sublabel: 'Hindi', flag: '🇮🇳', speechCode: 'hi-IN' },
  { code: 'en', label: 'English', sublabel: 'English', flag: '🇬🇧', speechCode: 'en-IN' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', sublabel: 'Punjabi', flag: '🌾', speechCode: 'pa-IN' },
  { code: 'mr', label: 'मराठी', sublabel: 'Marathi', flag: '🚩', speechCode: 'mr-IN' },
  { code: 'gu', label: 'ગુજરાતી', sublabel: 'Gujarati', flag: '🌿', speechCode: 'gu-IN' }
];

export const TRANSLATIONS = {
  hi: {
    appTitle: 'सहायक (Sahayak)',
    home: 'घर',
    schedule: 'तारीख',
    queue: 'नंबर',
    payment: 'रुपये',
    staffDesk: 'स्टाफ डेस्क',
    speak: 'बोलिए',
    talkToSathi: 'साथी AI • बोलिए',
    sathiAssistant: 'साथी AI सहायक',
    liveMandiData: 'लाइव मंडी डेटा',
    greeting: 'राम लाल जी, नमस्ते! 🙏 मैं आपका साथी AI सहायक हूँ। आज कोटा मंडी में गेहूं की खरीद ₹2,275/Qtl पर चालू है। आपका टोकन #42 है। आप बोलकर या लिखकर कुछ भी पूछ सकते हैं।',
    listening: 'सुन रहा हूँ... कृपया बोलिए',
    askOrType: 'सवाल लिखें या बोलें...',
    send: 'पूछें',
    stop: 'रोकें',
    listen: 'बोलकर सुनें',
    selectLanguage: 'भाषा चुनें • Select Language',
    todayOpen: 'आज खुला है',
    openToday: 'OPEN TODAY',
    gateOpen: 'गेट खुला है • Gate Open',
    gateClosed: 'गेट बंद है • Closed',
    wheatProcurement: 'गेहूं (Wheat) खरीद चालू',
    govtMsp: 'सरकारी समर्थन मूल्य (MSP)',
    bookSlot: 'स्लॉट बुक करें',
    bookSlotSubtitle: 'लाइन से बचें, समय पर पहुंचें',
    loadSize: 'वाहन व उपज भार',
    blockTokenNow: '🔒 टोकन अभी ब्लॉक करें',
    blockTokenSub: '15 मिनट के लिए आरक्षित • Free Slot Reserve',
    showQrPass: 'सुरक्षा गार्ड को पास दिखाएं',
    mandiSteps: 'मंडी प्रक्रिया • Mandi Steps',
    stepArrived: 'पहुंचे',
    stepWeighing: 'तौल',
    stepGrade: 'गुणवत्ता',
    stepPass: 'पास',
    stepCount: 'कदम 2 / 4 चालू',
    weighbridgeNo: 'निर्धारित कांटा',
    commodity: 'फसल • Commodity',
    vehicleDetails: 'ट्रैक्टर विवरण • Vehicle',
    totalApproved: 'कुल स्वीकृत राशि • Total Approved',
    needCashUrgently: 'पैसे तुरंत चाहिए? (Need Cash?)',
    getAdvanceNow: '⚡ तुरंत 80% पैसे लें • Get Money Now',
    advanceSubtext: 'बिना इंतजार 2 मिनट में अपने खाते में पाएं। शेष 20% सामान्य प्रक्रिया से मिलेगा।',
    linkedBank: 'जुड़ा हुआ बैंक खाता',
    verified: 'सत्यापित',
    mandiTaxFree: 'सरकारी मंडी शुल्क: ₹0 (किसान छूट)',
    zeroInterest: 'एडवांस शुल्क: 0% शून्य ब्याज (सरकारी योजना)',
    helpline: 'सहायता केंद्र: 1800-180-1551 (टोल फ्री)',
    portalTitle: 'किसान मंडी ई-उपार्जन पोर्टल • APMC कोटा',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'कृषि एवं किसान कल्याण मंत्रालय | Ministry of Agriculture & Farmers Welfare',
    nationalNetwork: 'राष्ट्रीय कृषि बाजार (e-NAM) अधिकृत APMC नेटवर्क',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    dashboardOverview: 'डैशबोर्ड / Overview',
    liveYardQueue: 'टोकन व कतार / Live Queue',
    scheduleRates: 'मंडी कैलेंडर व MSP / Schedule',
    payoutsPassbook: 'भुगतान व PFMS / Payouts',
    enamMarket: 'e-NAM नीलामी / Trade Slips',
    creditPassbook: 'क्रेडिट पासबुक / Passbook',
    staffControlDesk: 'स्टाफ कंट्रोल डेस्क / Staff Desk',
    dailyIntake: 'आज की कुल आवक',
    yourTokenStatus: 'आपका टोकन',
    approvedDbt: 'स्वीकृत DBT भुगतान',
    switchToMobile: 'मोबाइल व्यू (PWA)',
    switchToDesktop: 'डेस्कटॉप पोर्टल (Webpage)',
    printPass: 'दैनिक पास प्रिंट',
    getQrPass: 'गेट QR पास',
    searchPlaceholder: 'खोजें: टोकन सं., वाहन सं. (RJ-20-EA-4412), या किसान ID...',
    farmerName: 'राम लाल शर्मा',
    apmcKotaYard: 'APMC कोटा यार्ड',
    quintalUnit: 'क्विंटल',
    inflowDesc: '✓ 86 वाहन कोटा यार्ड में दर्ज',
    weighbridgeLane3: 'कांटा लेन 3',
    tractorsAhead: 'आगे केवल 4 ट्रैक्टर',
    soyabeanGrade: 'सोयाबीन JS-335 (Grade A)',
    advanceInstantAvail: '80% अग्रिम: ₹1,95,680 तुरंत उपलब्ध',
    entrySlipTitle: 'प्रवेश पर्ची व लाइव कतार बोर्ड',
    verifiedBatch: 'BATCH-24A • सत्यापित',
    yourToken: 'आपका टोकन',
    active: 'सक्रिय',
    registeredVehicleCrop: 'दर्ज वाहन व फसल',
    cropNameSoybean: 'सोयाबीन',
    goToWeighbridge: 'धर्मकांटा गेट क्र. 3 पर जाएं',
    estWaitTime: 'अनुमानित प्रतीक्षा समय',
    minutes: 'मिनट',
    atGateNow: 'गेट पर अभी',
    running: 'चालू',
    procurementPipeline: 'प्रोक्योरमेंट चरण ट्रैकिंग (4-Stage Pipeline)',
    step1Done: '1. प्रवेश व तौल (Done)',
    step2Progress: '2. गुणवत्ता जांच (In Progress)',
    step3Auction: '3. नीलामी आवंटन',
    step4Dbt: '4. DBT बैंक खाता',
    advanceSlotTitle: 'अग्रिम गेट स्लॉट बुकिंग (Advance Slot Reservation)',
    openStatus: 'खुला है • Open',
    morningWindow: 'प्रातः 09:00 - 11:00 AM',
    afternoonWindow: 'दोपहर 01:00 - 03:00 PM',
    morningSlotsAvail: '8 स्लॉट उपलब्ध (Morning Window)',
    afternoonSlotsAvail: '15 स्लॉट उपलब्ध (Afternoon Window)',
    confirmBookingBtn: 'नया टोकन आरक्षित करें (Confirm Booking)',
    bookingLoading: 'स्लॉट बुक हो रहा है...',
    instantAdvanceDesk: '80% त्वरित अग्रिम भुगतान Desk',
    approvedAdvanceAmount: 'स्वीकृत अग्रिम ऋण राशि',
    advanceSubDesc: 'तौल सत्यापन के तुरंत 15 मिनट के भीतर बैंक खाते में हस्तांतरण',
    grossCropVal: 'सकल फसल मूल्य:',
    advanceEligibility: 'अग्रिम पात्रता (80%):',
    interestRate: 'ब्याज दर (Subsidized):',
    beneficiaryAcc: 'लाभार्थी खाता:',
    disburseNow: '80% अग्रिम दावा करें (Disburse Now)',
    enamLiveBids: 'e-NAM लाइव बोलियां',
    viewAll: 'सभी देखें →',
    verifiedBuyer: 'सत्यापित खरीदार',
    perQuintal: 'प्रति क्विंटल',
    aboveMsp: 'above MSP',
    acceptBid: 'बोली स्वीकार करें',
    mandiEntrySlip: 'मंडी प्रवेश पर्ची व लाइव टोकन प्रबंधन',
    yardSubTitle: 'कोटा अनाज मंडी • लाइव धर्मकांटा लेन कतार',
    printSlip: 'पर्ची प्रिंट करें',
    viewQr: 'QR कोड देखें',
    officialGateSlip: 'आधिकारिक गेट प्रवेश पर्ची',
    apmcKotaRaj: 'कृषि उपज मंडी समिति • कोटा (राज.)',
    apmcSubSlip: 'APMC Gate Entry & Weighbridge Slip',
    verifiedStamp: '✓ सत्यापित / Verified',
    queueStatus: 'कतार स्थिति',
    estTime: 'अनुमानित समय',
    dailyMandiStatus: 'दैनिक मंडी संचालन स्थिति',
    mandiOpenToday: 'आज मंडी खुली है (Open Today)',
    operatingHours: 'प्रचालन समय',
    gateNo3: 'गेट क्र. 3',
    mainCrop: 'मुख्य अधिसूचित फसल:',
    upcomingDates: 'आगामी मंडी तिथियां व फसलें',
    tomorrowSat: 'कल • शनिवार (15 अप्रैल)',
    mustardMsp: 'सरसों (Mustard 42% Oil) • MSP ₹5,650',
    dayAfterSun: 'परसों • रविवार (16 अप्रैल)',
    mandiMaintenance: 'साप्ताहिक मंडी सफाई व रखरखाव',
    holidayClosed: 'अवकाश • Closed',
    pfmsDbtTitle: 'PFMS / DBT प्रत्यक्ष बैंक हस्तांतरण स्थिति',
    accountDetails: 'खाता सं.: SBI •••• 8821 • IFSC: SBIN0001234',
    claimAdvanceBtn: '80% अग्रिम दावा (₹1,95,680)',
    awaiting: 'प्रतीक्षारत',
    loadingPayment: 'भुगतान डेटा लोड हो रहा है...',
    tradeSlipsTitle: 'e-NAM मंडी नीलामी पर्चियां (Live Trade Slips)',
    activeBuyers: '42 सक्रिय पंजीकृत खरीदार • सीधा बोली स्वीकार करें',
    openFullMarket: 'फुल मार्केट लेजर खोलें',
    lotDetails: 'लॉट: #APMC-24A • 50 क्विंटल सोयाबीन',
    nabardTitle: 'NABARD-APMC किसान क्रेडिट पासबुक',
    approvedCreditLimit: 'स्वीकृत साख सीमा: ₹1,50,000 @ 4.0% p.a. ब्याज दर',
    viewPassbook: 'पासबुक लेजर देखें',
    kccVoucher: 'KCC फसल साख वाउचर',
    kccWithdrawable: '₹50,000 आहरण योग्य',
    kccSub: 'मंडी तौल टोकन पर तुरंत 0% प्रोसेसिंग शुल्क पर उपलब्ध।',
    enwrTitle: 'e-NWR भंडार गृह बंधक',
    enwrValue: '75% बाजार मूल्य अग्रिम',
    enwrSub: 'APMC गोदाम रसीद पर तुरंत बैंक क्रेडिट सुविधा।',
    pmfbyTitle: 'PMFBY फसल बीमा डेस्क',
    pmfbyZero: 'शून्य प्रीमियम कटौती',
    pmfbySub: 'स्वचालित मंडी गेट क्षतिपूर्ति सुरक्षा एवं क्लेम सहायता।',
    staffControlTitle: 'APMC मंडी कंट्रोल व ऑपरेटर डेस्क',
    staffControlSub: 'मंडी गेट स्थिति, लाइव कांटा कतार, और लाउडस्पीकर प्रसारण',
    staffAction1Title: '1. गेट स्थिति टॉगल',
    staffAction1Sub: 'मंडी यार्ड गेट की स्थिति को लाइव ओपन/क्लोज करें।',
    staffAction1Btn: 'गेट स्थिति बदलें (Open/Close)',
    staffAction2Title: '2. किसान चरण आगे बढ़ाएं',
    staffAction2Sub: 'किसान राम लाल (टोकन #42) को अगले चरण पर भेजें।',
    staffAction2Btn: 'अगला चरण (Advance Stage)',
    staffAction3Title: '3. लाउडस्पीकर घोषणा (PA)',
    staffAction3Sub: 'टोकन #42 को कांटा नंबर 3 पर आने की घोषणा करें।',
    staffAction3Btn: 'लाउडस्पीकर प्रसारण करें',
    footerRights: 'किसान मंडी (Kisan Mandi) • राष्ट्रीय ई-उपार्जन नेटवर्क • APMC कोटा अधिकृत',
    privacy: 'गोपनीयता नीति (Privacy)',
    terms: 'उपयोग की शर्तें (Terms)',
    footerMobileSwitch: '📱 मोबाइल ऐप व्यू में स्विच करें',
    chips: [
      'मेरी फसल कब बिकेगी?',
      'आज गेहूं का भाव क्या है?',
      'गाड़ी RJ-20-EA-4412 स्थिति',
      '80% एडवांस कैसे मिलेगा?'
    ]
  },
  en: {
    appTitle: 'Sahayak (सहायक)',
    home: 'Home',
    schedule: 'Schedule',
    queue: 'Token / Queue',
    payment: 'Payment',
    staffDesk: 'Staff Desk',
    speak: 'Speak',
    talkToSathi: 'Sathi AI • Talk',
    sathiAssistant: 'Sathi AI Assistant',
    liveMandiData: 'Live Mandi Data',
    greeting: 'Hello Ram Lal Ji! 🙏 I am your Sathi AI Assistant for Kota Mandi. Today Wheat MSP is ₹2,275/Qtl. Your Token is #42. How may I assist you today?',
    listening: 'Listening... Please speak now',
    askOrType: 'Type or speak your question...',
    send: 'Ask',
    stop: 'Stop',
    listen: 'Listen Aloud',
    selectLanguage: 'Select Language • भाषा चुनें',
    todayOpen: 'Open Today',
    openToday: 'OPEN TODAY',
    gateOpen: 'Gate Open',
    gateClosed: 'Gate Closed',
    wheatProcurement: 'Wheat Procurement Live',
    govtMsp: 'Govt. MSP Benchmark',
    bookSlot: "Book Today's Slot",
    bookSlotSubtitle: 'Skip the line, arrive on schedule',
    loadSize: 'Vehicle & Load Size',
    blockTokenNow: '🔒 Block Token Slot Now',
    blockTokenSub: 'Reserved for 15 mins • Priority Gate Pass',
    showQrPass: 'Show Entry QR Pass to Guard',
    mandiSteps: 'Mandi Steps Progress',
    stepArrived: 'Arrived',
    stepWeighing: 'Weighing',
    stepGrade: 'Grade',
    stepPass: 'Pass',
    stepCount: 'Step 2 / 4 Active',
    weighbridgeNo: 'Assigned Weighbridge',
    commodity: 'Commodity',
    vehicleDetails: 'Tractor Details',
    totalApproved: 'Total Approved Amount',
    needCashUrgently: 'Need Cash Urgently?',
    getAdvanceNow: '⚡ Get 80% Money Now',
    advanceSubtext: 'Get 80% within 120 seconds into your bank account. Remaining 20% processed normally.',
    linkedBank: 'Linked Bank Account',
    verified: 'Verified',
    mandiTaxFree: 'Mandi Fee: ₹0 (Farmer Exemption)',
    zeroInterest: 'Advance Fee: 0% Zero Interest (Govt. Scheme)',
    helpline: 'Helpdesk: 1800-180-1551 (Toll Free)',
    portalTitle: 'Kisan Mandi Digital Procurement Portal • APMC Kota',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'Ministry of Agriculture & Farmers Welfare | Government of India',
    nationalNetwork: 'National Agriculture Market (e-NAM) Authorized APMC Network',
    tollFree: 'Toll-Free Helpline',
    dashboardOverview: 'Dashboard / Overview',
    liveYardQueue: 'Live Yard Queue & Booking',
    scheduleRates: 'Mandi Schedule & MSP Rates',
    payoutsPassbook: 'Payouts & e-Passbook',
    enamMarket: 'e-NAM Auction Trade Slips',
    creditPassbook: 'KCC Credit Passbook',
    staffControlDesk: 'Staff Control Desk',
    dailyIntake: 'Total Daily Inflow',
    yourTokenStatus: 'Your Token Number',
    approvedDbt: 'Approved DBT Payout',
    switchToMobile: 'Mobile App View (PWA)',
    switchToDesktop: 'Desktop Web Portal',
    printPass: 'Print Daily Pass',
    getQrPass: 'Entry QR Pass',
    searchPlaceholder: 'Search: Token No., Vehicle No. (RJ-20-EA-4412), or Farmer ID...',
    farmerName: 'Ram Lal Sharma',
    apmcKotaYard: 'APMC Kota Yard',
    quintalUnit: 'Quintal',
    inflowDesc: '✓ 86 vehicles registered in Kota yard',
    weighbridgeLane3: 'Weighbridge Lane 3',
    tractorsAhead: 'Only 4 tractors ahead',
    soyabeanGrade: 'Soybean JS-335 (Grade A)',
    advanceInstantAvail: '80% Advance: ₹1,95,680 available instantly',
    entrySlipTitle: 'Gate Entry & Live Queue Board',
    verifiedBatch: 'BATCH-24A • VERIFIED',
    yourToken: 'Your Token',
    active: 'Active',
    registeredVehicleCrop: 'Registered Vehicle & Crop',
    cropNameSoybean: 'Soybean',
    goToWeighbridge: 'Proceed to Weighbridge Gate 3',
    estWaitTime: 'Estimated Wait Time',
    minutes: 'mins',
    atGateNow: 'At Gate Now',
    running: 'In Progress',
    procurementPipeline: 'Procurement Stage Tracking (4-Stage Pipeline)',
    step1Done: '1. Gate Entry & Weighment (Done)',
    step2Progress: '2. Quality Grading (In Progress)',
    step3Auction: '3. Auction Allocation',
    step4Dbt: '4. DBT Bank Transfer',
    advanceSlotTitle: 'Advance Gate Slot Reservation',
    openStatus: 'Open',
    morningWindow: 'Morning 09:00 - 11:00 AM',
    afternoonWindow: 'Afternoon 01:00 - 03:00 PM',
    morningSlotsAvail: '8 slots available (Morning Window)',
    afternoonSlotsAvail: '15 slots available (Afternoon Window)',
    confirmBookingBtn: 'Reserve Token (Confirm Booking)',
    bookingLoading: 'Booking Slot...',
    instantAdvanceDesk: '80% Instant Advance Payout Desk',
    approvedAdvanceAmount: 'Approved Advance Loan Amount',
    advanceSubDesc: 'Transferred directly to bank account within 15 mins of certified weighment',
    grossCropVal: 'Gross Crop Value:',
    advanceEligibility: 'Advance Eligibility (80%):',
    interestRate: 'Interest Rate (Subsidized):',
    beneficiaryAcc: 'Beneficiary Account:',
    disburseNow: 'Claim 80% Advance (Disburse Now)',
    enamLiveBids: 'e-NAM Live Bids',
    viewAll: 'View All →',
    verifiedBuyer: 'Verified Buyer',
    perQuintal: 'per Quintal',
    aboveMsp: 'above MSP',
    acceptBid: 'Accept Bid',
    mandiEntrySlip: 'Mandi Gate Entry Slip & Live Token Queue',
    yardSubTitle: 'Kota Grain Mandi • Live Weighbridge Lane Queue',
    printSlip: 'Print Slip',
    viewQr: 'View QR Code',
    officialGateSlip: 'Official APMC Gate Entry Slip',
    apmcKotaRaj: 'Agricultural Produce Market Committee • Kota (Raj.)',
    apmcSubSlip: 'APMC Gate Entry & Weighbridge Slip',
    verifiedStamp: '✓ Verified',
    queueStatus: 'Queue Position',
    estTime: 'Est. Wait',
    dailyMandiStatus: 'Daily Mandi Operations Status',
    mandiOpenToday: 'Mandi is Open Today',
    operatingHours: 'Operating Hours',
    gateNo3: 'Gate No. 3',
    mainCrop: 'Main Notified Crop:',
    upcomingDates: 'Upcoming Mandi Dates & Crops',
    tomorrowSat: 'Tomorrow • Saturday (Apr 15)',
    mustardMsp: 'Mustard (42% Oil) • MSP ₹5,650',
    dayAfterSun: 'Day After • Sunday (Apr 16)',
    mandiMaintenance: 'Weekly Mandi Cleaning & Maintenance',
    holidayClosed: 'Holiday • Closed',
    pfmsDbtTitle: 'PFMS / DBT Direct Bank Transfer Status',
    accountDetails: 'Acc: SBI •••• 8821 • IFSC: SBIN0001234',
    claimAdvanceBtn: 'Claim 80% Advance (₹1,95,680)',
    awaiting: 'Pending',
    loadingPayment: 'Loading payment data...',
    tradeSlipsTitle: 'e-NAM Mandi Auction Trade Slips',
    activeBuyers: '42 Active Registered Buyers • Instant Bid Acceptance',
    openFullMarket: 'Open Full Market Ledger',
    lotDetails: 'Lot: #APMC-24A • 50 Quintals Soybean',
    nabardTitle: 'NABARD-APMC Farmer Credit Passbook',
    approvedCreditLimit: 'Approved Credit Limit: ₹1,50,000 @ 4.0% p.a. interest',
    viewPassbook: 'View Passbook Ledger',
    kccVoucher: 'KCC Crop Credit Voucher',
    kccWithdrawable: '₹50,000 Available for Drawdown',
    kccSub: 'Instant drawdown on Mandi weighment token at 0% processing fee.',
    enwrTitle: 'e-NWR Electronic Warehouse Receipt',
    enwrValue: '75% Market Value Advance',
    enwrSub: 'Instant bank credit pledge against APMC warehouse storage receipts.',
    pmfbyTitle: 'PMFBY Crop Insurance Desk',
    pmfbyZero: 'Zero Premium Deduction',
    pmfbySub: 'Automated Mandi gate damage coverage and direct claim settlement.',
    staffControlTitle: 'APMC Mandi Control & Operator Desk',
    staffControlSub: 'Gate Status, Live Weighbridge Queue, and PA Announcements',
    staffAction1Title: '1. Gate Status Toggle',
    staffAction1Sub: 'Toggle Mandi yard gate status open or closed live.',
    staffAction1Btn: 'Toggle Gate Status (Open/Close)',
    staffAction2Title: '2. Advance Farmer Stage',
    staffAction2Sub: 'Advance Farmer Ram Lal (Token #42) to next stage.',
    staffAction2Btn: 'Advance Stage',
    staffAction3Title: '3. PA Loudspeaker Announcement',
    staffAction3Sub: 'Broadcast announcement for Token #42 to arrive at Weighbridge 3.',
    staffAction3Btn: 'Broadcast Announcement',
    footerRights: 'Kisan Mandi • National e-Procurement Network • APMC Kota Authorized',
    privacy: 'Privacy Policy',
    terms: 'Terms of Use',
    footerMobileSwitch: '📱 Switch to Mobile App View',
    chips: [
      'When will my crop be weighed?',
      "What is today's MSP rate?",
      'Check RJ-20-EA-4412 status',
      'How to get 80% advance?'
    ]
  },
  pa: {
    appTitle: 'ਸਹਾਇਕ (Sahayak)',
    home: 'ਘਰ',
    schedule: 'ਤਾਰੀਖ਼',
    queue: 'ਟੋਕਨ / ਕਤਾਰ',
    payment: 'ਭੁਗਤਾਨ',
    staffDesk: 'ਸਟਾਫ਼ ਡੈਸਕ',
    speak: 'ਬੋਲੋ',
    talkToSathi: 'ਸਾਥੀ AI • ਬੋਲੋ',
    sathiAssistant: 'ਸਾਥੀ AI ਸਹਾਇਕ',
    liveMandiData: 'ਲਾਈਵ ਮੰਡੀ ਡਾਟਾ',
    greeting: 'ਰਾਮ ਲਾਲ ਜੀ, ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ! 🙏 ਮੈਂ ਤੁਹਾਡਾ ਸਾਥੀ AI ਸਹਾਇਕ ਹਾਂ। ਅੱਜ ਕਣਕ ਦਾ ਐਮ.ਐਸ.ਪੀ ₹2,275/ਕੁਇੰਟਲ ਹੈ। ਤੁਹਾਡਾ ਟੋਕਨ #42 ਹੈ। ਤੁਸੀਂ ਕੁਝ ਵੀ ਪੁੱਛ ਸਕਦੇ ਹੋ।',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ... ਕਿਰਪਾ ਕਰਕੇ ਬੋਲੋ',
    askOrType: 'ਸਵਾਲ ਲਿਖੋ ਜਾਂ ਬੋਲੋ...',
    send: 'ਪੁੱਛੋ',
    stop: 'ਰੋਕੋ',
    listen: 'ਸੁਣੋ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ • Select Language',
    todayOpen: 'ਅੱਜ ਖੁੱਲ੍ਹਾ ਹੈ',
    openToday: 'OPEN TODAY',
    gateOpen: 'ਗੇਟ ਖੁੱਲ੍ਹਾ ਹੈ',
    gateClosed: 'ਗੇਟ ਬੰਦ ਹੈ',
    wheatProcurement: 'ਕਣਕ ਦੀ ਖ਼ਰੀਦ ਚਾਲੂ',
    govtMsp: 'ਸਰਕਾਰੀ ਸਮਰਥਨ ਮੁੱਲ (MSP)',
    bookSlot: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    bookSlotSubtitle: 'ਲਾਈਨ ਤੋਂ ਬਚੋ, ਸਮੇਂ ਸਿਰ ਪਹੁੰਚੋ',
    loadSize: 'ਵਾਹਨ ਅਤੇ ਫ਼ਸਲ ਭਾਰ',
    blockTokenNow: '🔒 ਟੋਕਨ ਹੁਣੇ ਬੁੱਕ ਕਰੋ',
    blockTokenSub: '15 ਮਿੰਟ ਲਈ ਰਾਖਵਾਂ • ਗੇਟ ਪਾਸ',
    showQrPass: 'ਗਾਰਡ ਨੂੰ QR ਪਾਸ ਦਿਖਾਓ',
    mandiSteps: 'ਮੰਡੀ ਕਦਮ • Mandi Steps',
    stepArrived: 'ਪਹੁੰਚੇ',
    stepWeighing: 'ਤੋਲ',
    stepGrade: 'ਕੁਆਲਿਟੀ',
    stepPass: 'ਪਾਸ',
    stepCount: 'ਕਦਮ 2 / 4 ਚਾਲੂ',
    weighbridgeNo: 'ਨਿਰਧਾਰਿਤ ਕੰਡਾ',
    commodity: 'ਫ਼ਸਲ • Commodity',
    vehicleDetails: 'ਟਰੈਕਟਰ ਵੇਰਵਾ',
    totalApproved: 'ਕੁੱਲ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਰਕਮ',
    needCashUrgently: 'ਪੈਸੇ ਦੀ ਤੁਰੰਤ ਲੋੜ ਹੈ?',
    getAdvanceNow: '⚡ 80% ਪੈਸੇ ਤੁਰੰਤ ਲਵੋ',
    advanceSubtext: '2 ਮਿੰਟਾਂ ਵਿੱਚ ਖਾਤੇ ਵਿੱਚ ਪ੍ਰਾਪਤ ਕਰੋ। ਬਾਕੀ 20% ਬਾਅਦ ਵਿੱਚ ਮਿਲੇਗਾ।',
    linkedBank: 'ਲਿੰਕ ਕੀਤਾ ਬੈਂਕ ਖਾਤਾ',
    verified: 'ਤਸਦੀਕਸ਼ੁਦਾ',
    mandiTaxFree: 'ਸਰਕਾਰੀ ਮੰਡੀ ਫੀਸ: ₹0 (ਛੋਟ)',
    zeroInterest: 'ਐਡਵਾਂਸ ਫੀਸ: 0% ਵਿਆਜ ਮੁਕਤ',
    helpline: 'ਹੈਲਪਲਾਈਨ: 1800-180-1551 (ਟੋਲ ਫ੍ਰੀ)',
    portalTitle: 'ਕਿਸਾਨ ਮੰਡੀ ਈ-ਖ਼ਰੀਦ ਪੋਰਟਲ • ਏ.ਪੀ.ਐਮ.ਸੀ ਕੋਟਾ',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ ਭਲਾਈ ਮੰਤਰਾਲਾ | Ministry of Agriculture',
    nationalNetwork: 'ਰਾਸ਼ਟਰੀ ਖੇਤੀਬਾੜੀ ਮੰਡੀ (e-NAM) ਨੈੱਟਵਰਕ',
    tollFree: 'ਟੋਲ-ਫ੍ਰੀ ਹੈਲਪਲਾਈਨ',
    dashboardOverview: 'ਡੈਸ਼ਬੋਰਡ / Overview',
    liveYardQueue: 'ਲਾਈਵ ਕਤਾਰ / Live Queue',
    scheduleRates: 'ਮੰਡੀ ਕੈਲੰਡਰ ਤੇ MSP / Schedule',
    payoutsPassbook: 'ਭੁਗਤਾਨ ਤੇ ਪਾਸਬੁੱਕ / Payouts',
    enamMarket: 'e-NAM ਨਿਲਾਮੀ / Trade Slips',
    creditPassbook: 'ਕ੍ਰੈਡਿਟ ਪਾਸਬੁੱਕ / Passbook',
    staffControlDesk: 'ਸਟਾਫ਼ ਡੈਸਕ / Staff Desk',
    dailyIntake: 'ਕੁੱਲ ਆਮਦ',
    yourTokenStatus: 'ਤੁਹਾਡਾ ਟੋਕਨ',
    approvedDbt: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ DBT ਭੁਗਤਾਨ',
    switchToMobile: 'ਮੋਬਾਈਲ ਵਿਊ (PWA)',
    switchToDesktop: 'ਡੈਸਕਟਾਪ ਪੋਰਟਲ',
    printPass: 'ਪਾਸ ਪ੍ਰਿੰਟ ਕਰੋ',
    getQrPass: 'QR ਪਾਸ ਦੇਖੋ',
    searchPlaceholder: 'ਖੋਜੋ: ਟੋਕਨ ਨੰ., ਗੱਡੀ ਨੰ. (RJ-20-EA-4412)...',
    farmerName: 'ਰਾਮ ਲਾਲ ਸ਼ਰਮਾ',
    apmcKotaYard: 'APMC ਕੋਟਾ ਯਾਰਡ',
    quintalUnit: 'ਕੁਇੰਟਲ',
    inflowDesc: '✓ 86 ਗੱਡੀਆਂ ਕੋਟਾ ਯਾਰਡ ਵਿੱਚ ਦਰਜ',
    weighbridgeLane3: 'ਕੰਡਾ ਲੇਨ 3',
    tractorsAhead: 'ਅੱਗੇ ਸਿਰਫ਼ 4 ਟਰੈਕਟਰ',
    soyabeanGrade: 'ਸੋਇਆਬੀਨ JS-335 (Grade A)',
    advanceInstantAvail: '80% ਐਡਵਾਂਸ: ₹1,95,680 ਤੁਰੰਤ ਉਪਲਬਧ',
    entrySlipTitle: 'ਦਾਖ਼ਲਾ ਪਰਚੀ ਅਤੇ ਲਾਈਵ ਕਤਾਰ ਬੋਰਡ',
    verifiedBatch: 'BATCH-24A • VERIFIED',
    yourToken: 'ਤੁਹਾਡਾ ਟੋਕਨ',
    active: 'ਸਰਗਰਮ',
    registeredVehicleCrop: 'ਦਰਜ ਵਾਹਨ ਅਤੇ ਫ਼ਸਲ',
    cropNameSoybean: 'ਸੋਇਆਬੀਨ',
    goToWeighbridge: 'ਕੰਡਾ ਗੇਟ ਨੰ. 3 ਤੇ ਜਾਓ',
    estWaitTime: 'ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ',
    minutes: 'ਮਿੰਟ',
    atGateNow: 'ਗੇਟ ਤੇ ਹੁਣ',
    running: 'ਚਾਲੂ',
    procurementPipeline: 'ਖ਼ਰੀਦ ਪ੍ਰਕਿਰਿਆ ਟ੍ਰੈਕਿੰਗ (4-Stage Pipeline)',
    step1Done: '1. ਦਾਖ਼ਲਾ ਅਤੇ ਤੋਲ (Done)',
    step2Progress: '2. ਗੁਣਵੱਤਾ ਜਾਂਚ (In Progress)',
    step3Auction: '3. ਨਿਲਾਮੀ ਵੰਡ',
    step4Dbt: '4. DBT ਬੈਂਕ ਖਾਤਾ',
    advanceSlotTitle: 'ਅਗਾਊਂ ਗੇਟ ਸਲਾਟ ਬੁਕਿੰਗ',
    openStatus: 'ਖੁੱਲ੍ਹਾ ਹੈ • Open',
    morningWindow: 'ਸਵੇਰੇ 09:00 - 11:00 AM',
    afternoonWindow: 'ਦੁਪਹਿਰ 01:00 - 03:00 PM',
    morningSlotsAvail: '8 ਸਲਾਟ ਉਪਲਬਧ (Morning Window)',
    afternoonSlotsAvail: '15 ਸਲਾਟ ਉਪਲਬਧ (Afternoon Window)',
    confirmBookingBtn: 'ਨਵਾਂ ਟੋਕਨ ਬੁੱਕ ਕਰੋ (Confirm Booking)',
    bookingLoading: 'ਸਲਾਟ ਬੁੱਕ ਹੋ ਰਿਹਾ ਹੈ...',
    instantAdvanceDesk: '80% ਤੁਰੰਤ ਐਡਵਾਂਸ ਭੁਗਤਾਨ ਡੈਸਕ',
    approvedAdvanceAmount: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਐਡਵਾਂਸ ਰਕਮ',
    advanceSubDesc: 'ਤੋਲ ਤਸਦੀਕ ਦੇ 15 ਮਿੰਟਾਂ ਦੇ ਅੰਦਰ ਬੈਂਕ ਖਾਤੇ ਵਿੱਚ ਟਰਾਂਸਫਰ',
    grossCropVal: 'ਕੁੱਲ ਫ਼ਸਲ ਮੁੱਲ:',
    advanceEligibility: 'ਐਡਵਾਂਸ ਯੋਗਤਾ (80%):',
    interestRate: 'ਵਿਆਜ ਦਰ (Subsidized):',
    beneficiaryAcc: 'ਲਾਭਪਾਤਰੀ ਖਾਤਾ:',
    disburseNow: '80% ਐਡਵਾਂਸ ਕਲੇਮ ਕਰੋ (Disburse Now)',
    enamLiveBids: 'e-NAM ਲਾਈਵ ਬੋਲੀਆਂ',
    viewAll: 'ਸਾਰੇ ਦੇਖੋ →',
    verifiedBuyer: 'ਤਸਦੀਕਸ਼ੁਦਾ ਖ਼ਰੀਦਦਾਰ',
    perQuintal: 'ਪ੍ਰਤੀ ਕੁਇੰਟਲ',
    aboveMsp: 'MSP ਤੋਂ ਵੱਧ',
    acceptBid: 'ਬੋਲੀ ਸਵੀਕਾਰ ਕਰੋ',
    mandiEntrySlip: 'ਮੰਡੀ ਦਾਖ਼ਲਾ ਪਰਚੀ ਅਤੇ ਟੋਕਨ ਪ੍ਰਬੰਧਨ',
    yardSubTitle: 'ਕੋਟਾ ਅਨਾਜ ਮੰਡੀ • ਲਾਈਵ ਕੰਡਾ ਲੇਨ ਕਤਾਰ',
    printSlip: 'ਪਰਚੀ ਪ੍ਰਿੰਟ ਕਰੋ',
    viewQr: 'QR ਕੋਡ ਦੇਖੋ',
    officialGateSlip: 'ਅਧਿਕਾਰਤ ਗੇਟ ਦਾਖ਼ਲਾ ਪਰਚੀ',
    apmcKotaRaj: 'ਖੇਤੀਬਾੜੀ ਉਪਜ ਮੰਡੀ ਕਮੇਟੀ • ਕੋਟਾ (ਰਾਜ.)',
    apmcSubSlip: 'APMC Gate Entry & Weighbridge Slip',
    verifiedStamp: '✓ ਤਸਦੀਕਸ਼ੁਦਾ',
    queueStatus: 'ਕਤਾਰ ਸਥਿਤੀ',
    estTime: 'ਅੰਦਾਜ਼ਨ ਸਮਾਂ',
    dailyMandiStatus: 'ਰੋਜ਼ਾਨਾ ਮੰਡੀ ਸੰਚਾਲਨ ਸਥਿਤੀ',
    mandiOpenToday: 'ਅੱਜ ਮੰਡੀ ਖੁੱਲ੍ਹੀ ਹੈ (Open Today)',
    operatingHours: 'ਕੰਮਕਾਜ ਦਾ ਸਮਾਂ',
    gateNo3: 'ਗੇਟ ਨੰ. 3',
    mainCrop: 'ਮੁੱਖ ਫ਼ਸਲ:',
    upcomingDates: 'ਆਉਣ ਵਾਲੀਆਂ ਮੰਡੀ ਤਾਰੀਖ਼ਾਂ',
    tomorrowSat: 'ਕੱਲ੍ਹ • ਸ਼ਨੀਵਾਰ (15 ਅਪ੍ਰੈਲ)',
    mustardMsp: 'ਸਰ੍ਹੋਂ (Mustard 42% Oil) • MSP ₹5,650',
    dayAfterSun: 'ਪਰਸੋਂ • ਐਤਵਾਰ (16 ਅਪ੍ਰੈਲ)',
    mandiMaintenance: 'ਹਫ਼ਤਾਵਾਰੀ ਸਫ਼ਾਈ ਅਤੇ ਰੱਖ-ਰਖਾਅ',
    holidayClosed: 'ਛੁੱਟੀ • Closed',
    pfmsDbtTitle: 'PFMS / DBT ਸਿੱਧਾ ਬੈਂਕ ਟਰਾਂਸਫਰ ਸਥਿਤੀ',
    accountDetails: 'ਖਾਤਾ ਨੰ: SBI •••• 8821 • IFSC: SBIN0001234',
    claimAdvanceBtn: '80% ਐਡਵਾਂਸ ਦਾਅਵਾ (₹1,95,680)',
    awaiting: 'ਉਡੀਕ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ',
    loadingPayment: 'ਭੁਗਤਾਨ ਡਾਟਾ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    tradeSlipsTitle: 'e-NAM ਮੰਡੀ ਨਿਲਾਮੀ ਪਰਚੀਆਂ',
    activeBuyers: '42 ਸਰਗਰਮ ਖ਼ਰੀਦਦਾਰ • ਬੋਲੀ ਸਵੀਕਾਰ ਕਰੋ',
    openFullMarket: 'ਪੂਰਾ ਮਾਰਕੀਟ ਲੇਜ਼ਰ ਖੋਲ੍ਹੋ',
    lotDetails: 'ਲਾਟ: #APMC-24A • 50 ਕੁਇੰਟਲ ਸੋਇਆਬੀਨ',
    nabardTitle: 'NABARD-APMC ਕਿਸਾਨ ਕ੍ਰੈਡਿਟ ਪਾਸਬੁੱਕ',
    approvedCreditLimit: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਕਰਜ਼ ਸੀਮਾ: ₹1,50,000 @ 4.0% p.a.',
    viewPassbook: 'ਪਾਸਬੁੱਕ ਲੇਜ਼ਰ ਦੇਖੋ',
    kccVoucher: 'KCC ਫ਼ਸਲ ਕ੍ਰੈਡਿਟ ਵਾਊਚਰ',
    kccWithdrawable: '₹50,000 ਕਢਵਾਉਣ ਯੋਗ',
    kccSub: 'ਮੰਡੀ ਤੋਲ ਟੋਕਨ ਤੇ 0% ਫੀਸ ਤੇ ਤੁਰੰਤ ਉਪਲਬਧ।',
    enwrTitle: 'e-NWR ਵੇਅਰਹਾਊਸ ਰਸੀਦ',
    enwrValue: '75% ਮਾਰਕੀਟ ਮੁੱਲ ਐਡਵਾਂਸ',
    enwrSub: 'ਗੋਦਾਮ ਰਸੀਦ ਤੇ ਤੁਰੰਤ ਬੈਂਕ ਕ੍ਰੈਡਿਟ ਸਹੂਲਤ।',
    pmfbyTitle: 'PMFBY ਫ਼ਸਲ ਬੀਮਾ ਡੈਸਕ',
    pmfbyZero: 'ਜ਼ੀਰੋ ਪ੍ਰੀਮੀਅਮ ਕਟੌਤੀ',
    pmfbySub: 'ਸਵੈ-ਚਾਲਿਤ ਮੰਡੀ ਗੇਟ ਮੁਆਵਜ਼ਾ ਸੁਰੱਖਿਆ।',
    staffControlTitle: 'APMC ਮੰਡੀ ਕੰਟਰੋਲ ਤੇ ਆਪਰੇਟਰ ਡੈਸਕ',
    staffControlSub: 'ਗੇਟ ਸਥਿਤੀ, ਲਾਈਵ ਕੰਡਾ ਕਤਾਰ, ਅਤੇ ਲਾਊਡਸਪੀਕਰ ਐਲਾਨ',
    staffAction1Title: '1. ਗੇਟ ਸਥਿਤੀ ਬਦਲੋ',
    staffAction1Sub: 'ਮੰਡੀ ਗੇਟ ਦੀ ਸਥਿਤੀ ਨੂੰ ਓਪਨ/ਕਲੋਜ਼ ਕਰੋ।',
    staffAction1Btn: 'ਗੇਟ ਸਥਿਤੀ ਬਦਲੋ (Open/Close)',
    staffAction2Title: '2. ਕਿਸਾਨ ਦਾ ਪੜਾਅ ਅੱਗੇ ਵਧਾਓ',
    staffAction2Sub: 'ਕਿਸਾਨ ਰਾਮ ਲਾਲ (ਟੋਕਨ #42) ਨੂੰ ਅਗਲੇ ਪੜਾਅ ਤੇ ਭੇਜੋ।',
    staffAction2Btn: 'ਅਗਲਾ ਪੜਾਅ (Advance Stage)',
    staffAction3Title: '3. ਲਾਊਡਸਪੀਕਰ ਐਲਾਨ (PA)',
    staffAction3Sub: 'ਟੋਕਨ #42 ਨੂੰ ਕੰਡਾ ਨੰਬਰ 3 ਤੇ ਆਉਣ ਦਾ ਐਲਾਨ ਕਰੋ।',
    staffAction3Btn: 'ਲਾਊਡਸਪੀਕਰ ਐਲਾਨ ਕਰੋ',
    footerRights: 'ਕਿਸਾਨ ਮੰਡੀ • ਰਾਸ਼ਟਰੀ ਈ-ਖ਼ਰੀਦ ਨੈੱਟਵਰਕ • APMC ਕੋਟਾ',
    privacy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ (Privacy)',
    terms: 'ਵਰਤੋਂ ਦੀਆਂ ਸ਼ਰਤਾਂ (Terms)',
    footerMobileSwitch: '📱 ਮੋਬਾਈਲ ਐਪ ਵਿਊ ਵਿੱਚ ਬਦਲੋ',
    chips: [
      'ਮੇਰੀ ਫ਼ਸਲ ਕਦੋਂ ਤੁਲੇਗੀ?',
      'ਅੱਜ ਕਣਕ ਦਾ ਕੀ ਭਾਅ ਹੈ?',
      'ਗੱਡੀ RJ-20-EA-4412 ਸਥਿਤੀ',
      '80% ਐਡਵਾਂਸ ਕਿਵੇਂ ਮਿਲੇਗਾ?'
    ]
  },
  mr: {
    appTitle: 'सहाय्यक (Sahayak)',
    home: 'मुख्य',
    schedule: 'वेळापत्रक',
    queue: 'टोकन / रांग',
    payment: 'पेमेंट',
    staffDesk: 'स्टाफ डेस्क',
    speak: 'बोला',
    talkToSathi: 'साथी AI • बोला',
    sathiAssistant: 'साथी AI सहाय्यक',
    liveMandiData: 'थेट बाजार माहिती',
    greeting: 'राम लाल जी, नमस्कार! 🙏 मी तुमचा साथी AI सहाय्यक आहे. आज कोटा बाजारात गव्हाचा दर ₹2,275/क्विंटल आहे. तुमचा टोकन #42 आहे. आपण काहीही विचारू शकता.',
    listening: 'ऐकत आहे... कृपया बोला',
    askOrType: 'प्रश्न लिहा किंवा बोला...',
    send: 'विचारा',
    stop: 'थांबवा',
    listen: 'ऐका',
    selectLanguage: 'भाषा निवडा • Select Language',
    todayOpen: 'आज सुरू आहे',
    openToday: 'OPEN TODAY',
    gateOpen: 'गेट उघडे आहे',
    gateClosed: 'गेट बंद आहे',
    wheatProcurement: 'गहू खरेदी सुरू',
    govtMsp: 'शासकीय हमीभाव (MSP)',
    bookSlot: 'स्लॉट बुक करा',
    bookSlotSubtitle: 'रांगेत उभे राहू नका, वेळेवर पोहोचा',
    loadSize: 'वाहन व वजन',
    blockTokenNow: '🔒 टोकन त्वरित आरक्षित करा',
    blockTokenSub: '15 मिनिटांसाठी राखीव • गेट पास',
    showQrPass: 'सुरक्षा रक्षकाला QR पास दाखवा',
    mandiSteps: 'बाजार प्रक्रिया टप्पे',
    stepArrived: 'आले',
    stepWeighing: 'वजन',
    stepGrade: 'गुणवत्ता',
    stepPass: 'पास',
    stepCount: 'टप्पा 2 / 4 सुरू',
    weighbridgeNo: 'काटा क्रमांक',
    commodity: 'पीक • Commodity',
    vehicleDetails: 'ट्रॅक्टर तपशील',
    totalApproved: 'एकूण मंजूर रक्कम',
    needCashUrgently: 'त्वरित पैशांची गरज आहे?',
    getAdvanceNow: '⚡ त्वरित 80% पैसे मिळवा',
    advanceSubtext: '2 मिनिटांत बँक खात्यात मिळवा. उर्वरित 20% नियमित प्रक्रियेने मिळेल.',
    linkedBank: 'जोडलेले बँक खाते',
    verified: 'सत्यापित',
    mandiTaxFree: 'शासकीय बाजार शुल्क: ₹0 (सूट)',
    zeroInterest: 'अ‍ॅडव्हान्स शुल्क: 0% व्याज (सरकारी योजना)',
    helpline: 'हेल्पलाइन: 1800-180-1551 (टोल फ्री)',
    portalTitle: 'किसान मंडी ई-खरेदी पोर्टल • APMC कोटा',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'कृषी आणि शेतकरी कल्याण मंत्रालय | Ministry of Agriculture',
    nationalNetwork: 'राष्ट्रीय कृषी बाजार (e-NAM) नेटवर्क',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    dashboardOverview: 'डॅशबोर्ड / Overview',
    liveYardQueue: 'थेट रांग / Live Queue',
    scheduleRates: 'बाजार वेळापत्रक व MSP',
    payoutsPassbook: 'पेमेंट व पासबुक / Payouts',
    enamMarket: 'e-NAM लिलाव / Trade Slips',
    creditPassbook: 'क्रेडिट पासबुक / Passbook',
    staffControlDesk: 'स्टाफ डेस्क / Staff Desk',
    dailyIntake: 'एकूण आवक',
    yourTokenStatus: 'तुमचा टोकन क्रमांक',
    approvedDbt: 'मंजूर DBT पेमेंट',
    switchToMobile: 'मोबाइल व्ह्यू (PWA)',
    switchToDesktop: 'डेस्कटॉप पोर्टल',
    printPass: 'पास प्रिंट करा',
    getQrPass: 'QR पास पहा',
    searchPlaceholder: 'शोधा: टोकन क्र., वाहन क्र. (RJ-20-EA-4412)...',
    farmerName: 'राम लाल शर्मा',
    apmcKotaYard: 'APMC कोटा यार्ड',
    quintalUnit: 'क्विंटल',
    inflowDesc: '✓ 86 वाहने कोटा यार्डमध्ये दाखल',
    weighbridgeLane3: 'काटा लेन 3',
    tractorsAhead: 'पुढे फक्त 4 ट्रॅक्टर',
    soyabeanGrade: 'सोयाबीन JS-335 (Grade A)',
    advanceInstantAvail: '80% अ‍ॅडव्हान्स: ₹1,95,680 त्वरित उपलब्ध',
    entrySlipTitle: 'प्रवेश पावती व थेट रांग बोर्ड',
    verifiedBatch: 'BATCH-24A • VERIFIED',
    yourToken: 'तुमचा टोकन',
    active: 'सक्रिय',
    registeredVehicleCrop: 'नोंदणीकृत वाहन व पीक',
    cropNameSoybean: 'सोयाबीन',
    goToWeighbridge: 'काटा गेट क्र. 3 वर जा',
    estWaitTime: 'अंदाजे प्रतीक्षा वेळ',
    minutes: 'मिनिटे',
    atGateNow: 'गेटवर आता',
    running: 'सुरू',
    procurementPipeline: 'खरेदी प्रक्रिया ट्रॅकिंग (4 टप्पे)',
    step1Done: '1. प्रवेश व वजन (Done)',
    step2Progress: '2. गुणवत्ता तपासणी (In Progress)',
    step3Auction: '3. लिलाव वाटप',
    step4Dbt: '4. DBT बँक खाते',
    advanceSlotTitle: 'आगाऊ गेट स्लॉट बुकिंग',
    openStatus: 'सुरू आहे • Open',
    morningWindow: 'सकाळी 09:00 - 11:00 AM',
    afternoonWindow: 'दुपारी 01:00 - 03:00 PM',
    morningSlotsAvail: '8 स्लॉट उपलब्ध (Morning Window)',
    afternoonSlotsAvail: '15 स्लॉट उपलब्ध (Afternoon Window)',
    confirmBookingBtn: 'टोकन आरक्षित करा (Confirm Booking)',
    bookingLoading: 'स्लॉट बुक होत आहे...',
    instantAdvanceDesk: '80% त्वरित अ‍ॅडव्हान्स पेमेंट डेस्क',
    approvedAdvanceAmount: 'मंजूर अ‍ॅडव्हान्स रक्कम',
    advanceSubDesc: 'वजन पडताळणीनंतर १५ मिनिटांत थेट बँक खात्यात जमा',
    grossCropVal: 'एकूण पीक मूल्य:',
    advanceEligibility: 'अ‍ॅडव्हान्स पात्रता (80%):',
    interestRate: 'व्याज दर (Subsidized):',
    beneficiaryAcc: 'लाभार्थी खाते:',
    disburseNow: '80% अ‍ॅडव्हान्स क्लेम करा (Disburse Now)',
    enamLiveBids: 'e-NAM थेट लिलाव',
    viewAll: 'सर्व पहा →',
    verifiedBuyer: 'सत्यापित खरेदीदार',
    perQuintal: 'प्रति क्विंटल',
    aboveMsp: 'MSP पेक्षा जास्त',
    acceptBid: 'बोली स्वीकारा',
    mandiEntrySlip: 'बाजार प्रवेश पावती व थेट टोकन व्यवस्थापन',
    yardSubTitle: 'कोटा धान्य बाजार • थेट काटा लेन रांग',
    printSlip: 'पावती प्रिंट करा',
    viewQr: 'QR कोड पहा',
    officialGateSlip: 'अधिकृत गेट प्रवेश पावती',
    apmcKotaRaj: 'कृषी उत्पन्न बाजार समिती • कोटा (राज.)',
    apmcSubSlip: 'APMC Gate Entry & Weighbridge Slip',
    verifiedStamp: '✓ पडताळलेले',
    queueStatus: 'रांग स्थिती',
    estTime: 'अंदाजे वेळ',
    dailyMandiStatus: 'दैनिक बाजार कामकाज स्थिती',
    mandiOpenToday: 'आज बाजार सुरू आहे (Open Today)',
    operatingHours: 'कामकाजाची वेळ',
    gateNo3: 'गेट क्र. 3',
    mainCrop: 'मुख्य अधिसूचित पीक:',
    upcomingDates: 'आगामी बाजार तारखा व पिके',
    tomorrowSat: 'उद्या • शनिवार (१५ एप्रिल)',
    mustardMsp: 'मोहरी (Mustard 42% Oil) • MSP ₹5,650',
    dayAfterSun: 'परवा • रविवार (१६ एप्रिल)',
    mandiMaintenance: 'साप्ताहिक बाजार स्वच्छता व देखभाल',
    holidayClosed: 'सुट्टी • Closed',
    pfmsDbtTitle: 'PFMS / DBT थेट बँक हस्तांतरण स्थिती',
    accountDetails: 'खाते क्र: SBI •••• 8821 • IFSC: SBIN0001234',
    claimAdvanceBtn: '80% अ‍ॅडव्हान्स दावा (₹1,95,680)',
    awaiting: 'प्रतीक्षेत',
    loadingPayment: 'पेमेंट डेटा लोड होत आहे...',
    tradeSlipsTitle: 'e-NAM बाजार लिलाव पावत्या',
    activeBuyers: '४२ सक्रिय नोंदणीकृत खरेदीदार • थेट बोली स्वीकारा',
    openFullMarket: 'पूर्ण मार्केट लेजर उघडा',
    lotDetails: 'लॉट: #APMC-24A • ५० क्विंटल सोयाबीन',
    nabardTitle: 'NABARD-APMC शेतकरी क्रेडिट पासबुक',
    approvedCreditLimit: 'मंजूर पत मर्यादा: ₹1,50,000 @ 4.0% p.a.',
    viewPassbook: 'पासबुक लेजर पहा',
    kccVoucher: 'KCC पीक पत व्हाउचर',
    kccWithdrawable: '₹50,000 काढण्यायोग्य',
    kccSub: 'बाजार वजन टोकनवर ०% शुल्कात त्वरित उपलब्ध.',
    enwrTitle: 'e-NWR गोदाम पावती',
    enwrValue: '७५% बाजार मूल्य अ‍ॅडव्हान्स',
    enwrSub: 'गोदाम पावतीवर त्वरित बँक पत सुविधा.',
    pmfbyTitle: 'PMFBY पीक विमा डेस्क',
    pmfbyZero: 'शून्य प्रीमियम कपात',
    pmfbySub: 'स्वयंचलित नुकसान भरपाई संरक्षण.',
    staffControlTitle: 'APMC बाजार नियंत्रण व ऑपरेटर डेस्क',
    staffControlSub: 'गेट स्थिती, काटा रांग आणि ध्वनिक्षेपक घोषणा',
    staffAction1Title: '1. गेट स्थिती टॉगल',
    staffAction1Sub: 'बाजार गेट स्थिती लाइव ओपन/क्लोज करा.',
    staffAction1Btn: 'गेट स्थिती बदला (Open/Close)',
    staffAction2Title: '2. शेतकरी टप्पा पुढे ढकला',
    staffAction2Sub: 'शेतकरी राम लाल (टोकन #42) पुढील टप्प्यावर पाठवा.',
    staffAction2Btn: 'पुढील टप्पा (Advance Stage)',
    staffAction3Title: '3. ध्वनिक्षेपक घोषणा (PA)',
    staffAction3Sub: 'टोकन #42 ला काटा क्र. 3 वर येण्याची घोषणा करा.',
    staffAction3Btn: 'ध्वनिक्षेपक घोषणा करा',
    footerRights: 'किसान मंडी • राष्ट्रीय ई-खरेदी नेटवर्क • APMC कोटा अधिकृत',
    privacy: 'गोपनीयता धोरण (Privacy)',
    terms: 'वापर अटी (Terms)',
    footerMobileSwitch: '📱 मोबाइल अ‍ॅप व्ह्यूवर स्विच करा',
    chips: [
      'माझे पीक कधी मोजले जाईल?',
      'आज गव्हाचा भाव काय आहे?',
      'गाडी RJ-20-EA-4412 स्थिती',
      '80% अ‍ॅडव्हान्स कसा मिळेल?'
    ]
  },
  gu: {
    appTitle: 'સહાયક (Sahayak)',
    home: 'મુખ્ય',
    schedule: 'તારીખ',
    queue: 'ટોકન / લાઈન',
    payment: 'ચુકવણી',
    staffDesk: 'સ્ટાફ ડેસ્ક',
    speak: 'બોલો',
    talkToSathi: 'સાથી AI • બોલો',
    sathiAssistant: 'સાથી AI સહાયક',
    liveMandiData: 'લાઈવ મંડી ડેટા',
    greeting: 'રામ લાલ જી, નમસ્તે! 🙏 હું તમારો સાથી AI સહાયક છું. આજે કોટા મંડીમાં ઘઉંનો ભાવ ₹2,275/ક્વિન્ટલ છે. તમારો ટોકન #42 છે. તમે બોલીને અથવા લખીને પૂછી શકો છો.',
    listening: 'સાંભળી રહ્યો છું... કૃપા કરીને બોલો',
    askOrType: 'પ્રશ્ન લખો અથવા બોલો...',
    send: 'પૂછો',
    stop: 'રોકો',
    listen: 'સાંભળો',
    selectLanguage: 'ભાષા પસંદ કરો • Select Language',
    todayOpen: 'આજે ખુલ્લું છે',
    openToday: 'OPEN TODAY',
    gateOpen: 'ગેટ ખુલ્લો છે',
    gateClosed: 'ગેટ બંધ છે',
    wheatProcurement: 'ઘઉંની ખરીદી ચાલુ',
    govtMsp: 'સરકારી ટેકાના ભાવ (MSP)',
    bookSlot: 'સ્લોટ બુક કરો',
    bookSlotSubtitle: 'લાઈન ટાળો, સમયસર પહોંચો',
    loadSize: 'વાહન અને જથ્થો',
    blockTokenNow: '🔒 ટોકન હમણાં જ બ્લોક કરો',
    blockTokenSub: '15 મિનિટ માટે અનામત • ગેટ પાસ',
    showQrPass: 'સુરક્ષા ગાર્ડને QR પાસ બતાવો',
    mandiSteps: 'મંડી પ્રક્રિયા પગલાં',
    stepArrived: 'પહોંચ્યા',
    stepWeighing: 'તોલ',
    stepGrade: 'ગુણવત્તા',
    stepPass: 'પાસ',
    stepCount: 'પગલું 2 / 4 ચાલુ',
    weighbridgeNo: 'નિયુક્ત કાંટો',
    commodity: 'પાક • Commodity',
    vehicleDetails: 'ટ્રેક્ટર વિગતો',
    totalApproved: 'કુલ મંજૂર રકમ',
    needCashUrgently: 'ત્વરિત પૈસાની જરૂર છે?',
    getAdvanceNow: '⚡ 80% પૈસા તરત મેળવો',
    advanceSubtext: '2 મિનિટમાં તમારા ખાતામાં મેળવો. બાકીના 20% સામાન્ય રીતે મળશે.',
    linkedBank: 'જોડાયેલ બેંક ખાતું',
    verified: 'ચકાસાયેલ',
    mandiTaxFree: 'સરકારી મંડી ફી: ₹0 (ખેડૂત છૂટ)',
    zeroInterest: 'એડવાન્સ ફી: 0% વ્યાજ (સરકારી યોજના)',
    helpline: 'હેલ્પલાઇન: 1800-180-1551 (ટોલ ફ્રી)',
    portalTitle: 'કિસાન મંડી ઈ-ખરીદી પોર્ટલ • APMC કોટા',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'કૃષિ અને ખેડૂત કલ્યાણ મંત્રાલય | Ministry of Agriculture',
    nationalNetwork: 'રાષ્ટ્રીય કૃષિ બજાર (e-NAM) નેટવર્ક',
    tollFree: 'ટોલ-ફ્રી હેલ્પલાઇન',
    dashboardOverview: 'ડેશબોર્ડ / Overview',
    liveYardQueue: 'લાઈવ લાઈન / Live Queue',
    scheduleRates: 'મંડી કેલેન્ડર અને MSP',
    payoutsPassbook: 'ચુકવણી અને પાસબુક / Payouts',
    enamMarket: 'e-NAM હરાજી / Trade Slips',
    creditPassbook: 'ક્રેડિટ પાસબુક / Passbook',
    staffControlDesk: 'સ્ટાફ ડેસ્ક / Staff Desk',
    dailyIntake: 'કુલ આવક',
    yourTokenStatus: 'તમારો ટોકન',
    approvedDbt: 'મંજૂર થયેલ DBT ચુકવણી',
    switchToMobile: 'મોબાઇલ વ્યૂ (PWA)',
    switchToDesktop: 'ડેસ્કટોપ પોર્ટલ',
    printPass: 'પાસ પ્રિન્ટ કરો',
    getQrPass: 'QR પાસ જુઓ',
    searchPlaceholder: 'શોધો: ટોકન નં., વાહન નં. (RJ-20-EA-4412)...',
    farmerName: 'રામ લાલ શર્મા',
    apmcKotaYard: 'APMC કોટા યાર્ડ',
    quintalUnit: 'ક્વિન્ટલ',
    inflowDesc: '✓ 86 વાહનો કોટા યાર્ડમાં નોંધાયેલ',
    weighbridgeLane3: 'કાંટો લેન 3',
    tractorsAhead: 'આગળ માત્ર 4 ટ્રેક્ટર',
    soyabeanGrade: 'સોયાબીન JS-335 (Grade A)',
    advanceInstantAvail: '80% એડવાન્સ: ₹1,95,680 તરત ઉપલબ્ધ',
    entrySlipTitle: 'પ્રવેશ પહોંચ અને લાઈવ લાઈન બોર્ડ',
    verifiedBatch: 'BATCH-24A • VERIFIED',
    yourToken: 'તમારો ટોકન',
    active: 'સક્રિય',
    registeredVehicleCrop: 'નોંધાયેલ વાહન અને પાક',
    cropNameSoybean: 'સોયાબીન',
    goToWeighbridge: 'કાંટો ગેટ નં. 3 પર જાઓ',
    estWaitTime: 'અંદાજિત પ્રતીક્ષા સમય',
    minutes: 'મિનિટ',
    atGateNow: 'ગેટ પર અત્યારે',
    running: 'ચાલુ',
    procurementPipeline: 'ખરીદ પ્રક્રિયા ટ્રેકિંગ (4 તબક્કા)',
    step1Done: '1. પ્રવેશ અને તોલ (Done)',
    step2Progress: '2. ગુણવત્તા ચકાસણી (In Progress)',
    step3Auction: '3. હરાજી ફાળવણી',
    step4Dbt: '4. DBT બેંક ખાતું',
    advanceSlotTitle: 'અગાઉથી ગેટ સ્લોટ બુકિંગ',
    openStatus: 'ખુલ્લું છે • Open',
    morningWindow: 'સવારે 09:00 - 11:00 AM',
    afternoonWindow: 'બપોરે 01:00 - 03:00 PM',
    morningSlotsAvail: '8 સ્લોટ ઉપલબ્ધ (Morning Window)',
    afternoonSlotsAvail: '15 સ્લોટ ઉપલબ્ધ (Afternoon Window)',
    confirmBookingBtn: 'નવો ટોકન બુક કરો (Confirm Booking)',
    bookingLoading: 'સ્લોટ બુક થઈ રહ્યો છે...',
    instantAdvanceDesk: '80% ત્વરિત એડવાન્સ ચુકવણી ડેસ્ક',
    approvedAdvanceAmount: 'મંજૂર એડવાન્સ રકમ',
    advanceSubDesc: 'તોલ ચકાસણી પછી 15 મિનિટમાં સીધા બેંક ખાતામાં જમા',
    grossCropVal: 'કુલ પાક મૂલ્ય:',
    advanceEligibility: 'એડવાન્સ પાત્રતા (80%):',
    interestRate: 'વ્યાજ દર (Subsidized):',
    beneficiaryAcc: 'લાભાર્થી ખાતું:',
    disburseNow: '80% એડવાન્સ ક્લેમ કરો (Disburse Now)',
    enamLiveBids: 'e-NAM લાઈવ બોલીઓ',
    viewAll: 'બધા જુઓ →',
    verifiedBuyer: 'ચકાસાયેલ ખરીદદાર',
    perQuintal: 'પ્રતિ ક્વિન્ટલ',
    aboveMsp: 'MSP થી વધુ',
    acceptBid: 'બોલી સ્વીકારો',
    mandiEntrySlip: 'મંડી પ્રવેશ પહોંચ અને લાઈવ ટોકન વ્યવસ્થાપન',
    yardSubTitle: 'કોટા અનાજ મંડી • લાઈવ કાંટો લાઈન',
    printSlip: 'પહોંચ પ્રિન્ટ કરો',
    viewQr: 'QR કોડ જુઓ',
    officialGateSlip: 'સત્તાવાર ગેટ પ્રવેશ પહોંચ',
    apmcKotaRaj: 'ખેતીવાડી ઉત્પન્ન બજાર સમિતિ • કોટા (રાજ.)',
    apmcSubSlip: 'APMC Gate Entry & Weighbridge Slip',
    verifiedStamp: '✓ ચકાસાયેલ',
    queueStatus: 'લાઈન સ્થિતિ',
    estTime: 'અંદાજિત સમય',
    dailyMandiStatus: 'દૈનિક મંડી સંચાલન સ્થિતિ',
    mandiOpenToday: 'આજે મંડી ખુલ્લી છે (Open Today)',
    operatingHours: 'કામકાજનો સમય',
    gateNo3: 'ગેટ નં. 3',
    mainCrop: 'મુખ્ય પાક:',
    upcomingDates: 'આગામી મંડી તારીખો અને પાક',
    tomorrowSat: 'આવતીકાલે • શનિવાર (15 એપ્રિલ)',
    mustardMsp: 'રાયડો (Mustard 42% Oil) • MSP ₹5,650',
    dayAfterSun: 'પરમદિવસે • રવિવાર (16 એપ્રિલ)',
    mandiMaintenance: 'સાપ્તાહિક મંડી સફાઈ અને જાળવણી',
    holidayClosed: 'રજા • Closed',
    pfmsDbtTitle: 'PFMS / DBT સીધા બેંક ટ્રાન્સફર સ્થિતિ',
    accountDetails: 'ખાતા નં: SBI •••• 8821 • IFSC: SBIN0001234',
    claimAdvanceBtn: '80% એડવાન્સ દાવો (₹1,95,680)',
    awaiting: 'બાકી છે',
    loadingPayment: 'ચુકવણી ડેટા લોડ થઈ રહ્યો છે...',
    tradeSlipsTitle: 'e-NAM મંડી હરાજી પહોંચ',
    activeBuyers: '42 સક્રિય નોંધાયેલ ખરીદદારો • સીધી બોલી સ્વીકારો',
    openFullMarket: 'સંપૂર્ણ માર્કેટ લેજર ખોલો',
    lotDetails: 'લોટ: #APMC-24A • 50 ક્વિન્ટલ સોયાબીન',
    nabardTitle: 'NABARD-APMC ખેડૂત ક્રેડિટ પાસબુક',
    approvedCreditLimit: 'મંજૂર ક્રેડિટ લિમિટ: ₹1,50,000 @ 4.0% p.a.',
    viewPassbook: 'પાસબુક લેજર જુઓ',
    kccVoucher: 'KCC પાક ક્રેડિટ વાઉચર',
    kccWithdrawable: '₹50,000 ઉપાડવા યોગ્ય',
    kccSub: 'મંડી તોલ ટોકન પર 0% પ્રોસેસિંગ ફી પર તરત ઉપલબ્ધ.',
    enwrTitle: 'e-NWR વેરહાઉસ રસીદ',
    enwrValue: '75% બજાર મૂલ્ય એડવાન્સ',
    enwrSub: 'ગોદામ રસીદ પર તરત બેંક ક્રેડિટ સુવિધા.',
    pmfbyTitle: 'PMFBY પાક વીમા ડેસ્ક',
    pmfbyZero: 'શૂન્ય પ્રીમિયમ કપાત',
    pmfbySub: 'ઓટોમેટેડ મંડી ગેટ વળતર સુરક્ષા.',
    staffControlTitle: 'APMC મંડી કંટ્રોલ અને ઓપરેટર ડેસ્ક',
    staffControlSub: 'ગેટ સ્થિતિ, કાંટો લાઈન અને લાઉડસ્પીકર ઘોષણા',
    staffAction1Title: '1. ગેટ સ્થિતિ બદલો',
    staffAction1Sub: 'મંડી ગેટ સ્થિતિ લાઈવ ઓપન/ક્લોઝ કરો.',
    staffAction1Btn: 'ગેટ સ્થિતિ બદલો (Open/Close)',
    staffAction2Title: '2. ખેડૂત તબક્કો આગળ વધારો',
    staffAction2Sub: 'ખેડૂત રામ લાલ (ટોકન #42) ને આગળના તબક્કે મોકલો.',
    staffAction2Btn: 'આગળનો તબક્કો (Advance Stage)',
    staffAction3Title: '3. લાઉડસ્પીકર ઘોષણા (PA)',
    staffAction3Sub: 'ટોકન #42 ને કાંટો નં. 3 પર આવવાની ઘોષણા કરો.',
    staffAction3Btn: 'લાઉડસ્પીકર ઘોષણા કરો',
    footerRights: 'કિસાન મંડી • રાષ્ટ્રીય ઈ-ખરીદી નેટવર્ક • APMC કોટા',
    privacy: 'ગોપનીયતા નીતિ (Privacy)',
    terms: 'વાપરવાની શરતો (Terms)',
    footerMobileSwitch: '📱 મોબાઇલ એપ વ્યૂમાં સ્વિચ કરો',
    chips: [
      'મારો પાક ક્યારે તોલાશે?',
      'આજે ઘઉંનો ભાવ શું છે?',
      'વાહન RJ-20-EA-4412 સ્થિતિ',
      '80% એડવાન્સ કેવી રીતે મળશે?'
    ]
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('kisan_mandi_language') || 'hi';
  });

  const [isLangModalOpen, setIsLangModalOpen] = useState(false);

  const changeLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem('kisan_mandi_language', langCode);
      setIsLangModalOpen(false);
    }
  };

  const currentLangObj = LANGUAGES.find((l) => l.code === currentLang) || LANGUAGES[0];

  const t = (key, fallback = '') => {
    const dict = TRANSLATIONS[currentLang] || TRANSLATIONS.hi;
    return dict[key] !== undefined ? dict[key] : fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        currentLangObj,
        changeLanguage,
        isLangModalOpen,
        setIsLangModalOpen,
        t,
        LANGUAGES,
        speechCode: currentLangObj.speechCode
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
