import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'hi', label: 'हिन्दी', sublabel: 'Hindi', flag: '🇮🇳', speechCode: 'hi-IN' },
  { code: 'en', label: 'English', sublabel: 'English', flag: '🇬🇧', speechCode: 'en-IN' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ', sublabel: 'Punjabi', flag: '🌾', speechCode: 'pa-IN' },
  { code: 'mr', label: 'मराठी', sublabel: 'Marathi', flag: '🚩', speechCode: 'mr-IN' },
  { code: 'gu', label: 'ગુજરાતી', sublabel: 'Gujarati', flag: '🌿', speechCode: 'gu-IN' }
];

export const TRANSLATIONS = {
  hi: {
    appTitle: 'किसान मंडी',
    home: 'घर',
    schedule: 'तारीख',
    queue: 'नंबर',
    payment: 'रुपये',
    staffDesk: 'स्टाफ डेस्क',
    speak: 'बोलिए',
    talkToSathi: 'साथी AI • बोलिए',
    sathiAssistant: 'साथी AI सहायक',
    liveMandiData: 'लाइव मंडी डेटा',
    greeting: 'राम लाल जी, नमस्ते! 🙏 मैं आपका साथी AI सहायक हूँ। आज कोटा मंडी में गेहूं की खरीद ₹2,275/Qtl पर चालू है। आपका टोकन #42 है। आप बोलकर या लिखकर कुछ भी पूछ सकते हैं।',
    listening: 'सुन रहा हूँ... कृपया बोलिए',
    askOrType: 'सवाल लिखें या बोलें...',
    send: 'पूछें',
    stop: 'रोकें',
    listen: 'बोलकर सुनें',
    selectLanguage: 'भाषा चुनें • Select Language',
    todayOpen: 'आज खुला है',
    openToday: 'OPEN TODAY',
    gateOpen: 'गेट खुला है • Gate Open',
    gateClosed: 'गेट बंद है • Closed',
    wheatProcurement: 'गेहूं (Wheat) खरीद चालू',
    govtMsp: 'सरकारी समर्थन मूल्य (MSP)',
    bookSlot: 'स्लॉट बुक करें',
    bookSlotSubtitle: 'लाइन से बचें, समय पर पहुंचें',
    loadSize: 'वाहन व उपज भार',
    blockTokenNow: '🔒 टोकन अभी ब्लॉक करें',
    blockTokenSub: '15 मिनट के लिए आरक्षित • Free Slot Reserve',
    showQrPass: 'सुरक्षा गार्ड को पास दिखाएं',
    mandiSteps: 'मंडी प्रक्रिया • Mandi Steps',
    stepArrived: 'पहुंचे',
    stepWeighing: 'तौल',
    stepGrade: 'गुणवत्ता',
    stepPass: 'पास',
    stepCount: 'कदम 2 / 4 चालू',
    weighbridgeNo: 'निर्धारित कांटा',
    commodity: 'फसल • Commodity',
    vehicleDetails: 'ट्रैक्टर विवरण • Vehicle',
    totalApproved: 'कुल स्वीकृत राशि • Total Approved',
    needCashUrgently: 'पैसे तुरंत चाहिए? (Need Cash?)',
    getAdvanceNow: '⚡ तुरंत 80% पैसे लें • Get Money Now',
    advanceSubtext: 'बिना इंतजार 2 मिनट में अपने खाते में पाएं। शेष 20% सामान्य प्रक्रिया से मिलेगा।',
    linkedBank: 'जुड़ा हुआ बैंक खाता',
    verified: 'सत्यापित',
    mandiTaxFree: 'सरकारी मंडी शुल्क: ₹0 (किसान छूट)',
    zeroInterest: 'एडवांस शुल्क: 0% शून्य ब्याज (सरकारी योजना)',
    helpline: 'सहायता केंद्र: 1800-180-1551 (टोल फ्री)',
    portalTitle: 'किसान मंडी ई-उपार्जन पोर्टल • APMC कोटा',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'कृषि एवं किसान कल्याण मंत्रालय | Ministry of Agriculture & Farmers Welfare',
    nationalNetwork: 'राष्ट्रीय कृषि बाजार (e-NAM) अधिकृत APMC नेटवर्क',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    dashboardOverview: 'डैशबोर्ड / Overview',
    liveYardQueue: 'टोकन व कतार / Live Queue',
    scheduleRates: 'मंडी कैलेंडर व MSP / Schedule',
    payoutsPassbook: 'भुगतान व PFMS / Payouts',
    enamMarket: 'e-NAM नीलामी / Trade Slips',
    creditPassbook: 'क्रेडिट पासबुक / Passbook',
    staffControlDesk: 'स्टाफ कंट्रोल डेस्क / Staff Desk',
    dailyIntake: 'आज की कुल आवक (Daily Intake)',
    yourTokenStatus: 'आपका टोकन क्रमांक',
    approvedDbt: 'स्वीकृत DBT भुगतान',
    switchToMobile: 'मोबाइल व्यू (PWA)',
    switchToDesktop: 'डेस्कटॉप पोर्टल (Webpage)',
    printPass: 'दैनिक पास प्रिंट',
    getQrPass: 'गेट QR पास',
    searchPlaceholder: 'खोजें: टोकन सं., वाहन सं. (RJ-20-EA-4412), या किसान ID...',
    chips: [
      'मेरी फसल कब बिकेगी?',
      'आज गेहूं का भाव क्या है?',
      'गाड़ी RJ-20-EA-4412 स्थिति',
      '80% एडवांस कैसे मिलेगा?'
    ]
  },
  en: {
    appTitle: 'Kisan Mandi',
    home: 'Home',
    schedule: 'Schedule',
    queue: 'Token / Queue',
    payment: 'Payment',
    staffDesk: 'Staff Desk',
    speak: 'Speak',
    talkToSathi: 'Sathi AI • Talk',
    sathiAssistant: 'Sathi AI Assistant',
    liveMandiData: 'Live Mandi Data',
    greeting: 'Hello Ram Lal Ji! 🙏 I am your Sathi AI Assistant for Kota Mandi. Today Wheat MSP is ₹2,275/Qtl. Your Token is #42. How may I assist you today?',
    listening: 'Listening... Please speak now',
    askOrType: 'Type or speak your question...',
    send: 'Ask',
    stop: 'Stop',
    listen: 'Listen Aloud',
    selectLanguage: 'Select Language • भाषा चुनें',
    todayOpen: 'Open Today',
    openToday: 'OPEN TODAY',
    gateOpen: 'Gate Open',
    gateClosed: 'Gate Closed',
    wheatProcurement: 'Wheat Procurement Live',
    govtMsp: 'Govt. MSP Benchmark',
    bookSlot: "Book Today's Slot",
    bookSlotSubtitle: 'Skip the line, arrive on schedule',
    loadSize: 'Vehicle & Load Size',
    blockTokenNow: '🔒 Block Token Slot Now',
    blockTokenSub: 'Reserved for 15 mins • Priority Gate Pass',
    showQrPass: 'Show Entry QR Pass to Guard',
    mandiSteps: 'Mandi Steps Progress',
    stepArrived: 'Arrived',
    stepWeighing: 'Weighing',
    stepGrade: 'Grade',
    stepPass: 'Pass',
    stepCount: 'Step 2 / 4 Active',
    weighbridgeNo: 'Assigned Weighbridge',
    commodity: 'Commodity',
    vehicleDetails: 'Tractor Details',
    totalApproved: 'Total Approved Amount',
    needCashUrgently: 'Need Cash Urgently?',
    getAdvanceNow: '⚡ Get 80% Money Now',
    advanceSubtext: 'Get 80% within 120 seconds into your bank account. Remaining 20% processed normally.',
    linkedBank: 'Linked Bank Account',
    verified: 'Verified',
    mandiTaxFree: 'Mandi Fee: ₹0 (Farmer Exemption)',
    zeroInterest: 'Advance Fee: 0% Zero Interest (Govt. Scheme)',
    helpline: 'Helpdesk: 1800-180-1551 (Toll Free)',
    portalTitle: 'Kisan Mandi Digital Procurement Portal • APMC Kota',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'Ministry of Agriculture & Farmers Welfare | Government of India',
    nationalNetwork: 'National Agriculture Market (e-NAM) Authorized APMC Network',
    tollFree: 'Toll-Free Helpline',
    dashboardOverview: 'Dashboard / Overview',
    liveYardQueue: 'Live Yard Queue & Booking',
    scheduleRates: 'Mandi Schedule & MSP Rates',
    payoutsPassbook: 'Payouts & e-Passbook',
    enamMarket: 'e-NAM Auction Trade Slips',
    creditPassbook: 'KCC Credit Passbook',
    staffControlDesk: 'Staff Control Desk',
    dailyIntake: 'Total Daily Inflow',
    yourTokenStatus: 'Your Token Number',
    approvedDbt: 'Approved DBT Payout',
    switchToMobile: 'Mobile App View (PWA)',
    switchToDesktop: 'Desktop Web Portal',
    printPass: 'Print Daily Pass',
    getQrPass: 'Entry QR Pass',
    searchPlaceholder: 'Search: Token No., Vehicle No. (RJ-20-EA-4412), or Farmer ID...',
    chips: [
      'When will my crop be weighed?',
      "What is today's MSP rate?",
      'Check RJ-20-EA-4412 status',
      'How to get 80% advance?'
    ]
  },
  pa: {
    appTitle: 'ਕਿਸਾਨ ਮੰਡੀ',
    home: 'ਘਰ',
    schedule: 'ਤਾਰੀਖ਼',
    queue: 'ਟੋਕਨ / ਕਤਾਰ',
    payment: 'ਭੁਗਤਾਨ',
    staffDesk: 'ਸਟਾਫ਼ ਡੈਸਕ',
    speak: 'ਬੋਲੋ',
    talkToSathi: 'ਸਾਥੀ AI • ਬੋਲੋ',
    sathiAssistant: 'ਸਾਥੀ AI ਸਹਾਇਕ',
    liveMandiData: 'ਲਾਈਵ ਮੰਡੀ ਡਾਟਾ',
    greeting: 'ਰਾਮ ਲਾਲ ਜੀ, ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ! 🙏 ਮੈਂ ਤੁਹਾਡਾ ਸਾਥੀ AI ਸਹਾਇਕ ਹਾਂ। ਅੱਜ ਕਣਕ ਦਾ ਐਮ.ਐਸ.ਪੀ ₹2,275/ਕੁਇੰਟਲ ਹੈ। ਤੁਹਾਡਾ ਟੋਕਨ #42 ਹੈ। ਤੁਸੀਂ ਕੁਝ ਵੀ ਪੁੱਛ ਸਕਦੇ ਹੋ।',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ... ਕਿਰਪਾ ਕਰਕੇ ਬੋਲੋ',
    askOrType: 'ਸਵਾਲ ਲਿਖੋ ਜਾਂ ਬੋਲੋ...',
    send: 'ਪੁੱਛੋ',
    stop: 'ਰੋਕੋ',
    listen: 'ਸੁਣੋ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ • Select Language',
    todayOpen: 'ਅੱਜ ਖੁੱਲ੍ਹਾ ਹੈ',
    openToday: 'OPEN TODAY',
    gateOpen: 'ਗੇਟ ਖੁੱਲ੍ਹਾ ਹੈ',
    gateClosed: 'ਗੇਟ ਬੰਦ ਹੈ',
    wheatProcurement: 'ਕਣਕ ਦੀ ਖ਼ਰੀਦ ਚਾਲੂ',
    govtMsp: 'ਸਰਕਾਰੀ ਸਮਰਥਨ ਮੁੱਲ (MSP)',
    bookSlot: 'ਸਲਾਟ ਬੁੱਕ ਕਰੋ',
    bookSlotSubtitle: 'ਲਾਈਨ ਤੋਂ ਬਚੋ, ਸਮੇਂ ਸਿਰ ਪਹੁੰਚੋ',
    loadSize: 'ਵਾਹਨ ਅਤੇ ਫ਼ਸਲ ਭਾਰ',
    blockTokenNow: '🔒 ਟੋਕਨ ਹੁਣੇ ਬੁੱਕ ਕਰੋ',
    blockTokenSub: '15 ਮਿੰਟ ਲਈ ਰਾਖਵਾਂ • ਗੇਟ ਪਾਸ',
    showQrPass: 'ਗਾਰਡ ਨੂੰ QR ਪਾਸ ਦਿਖਾਓ',
    mandiSteps: 'ਮੰਡੀ ਕਦਮ • Mandi Steps',
    stepArrived: 'ਪਹੁੰਚੇ',
    stepWeighing: 'ਤੋਲ',
    stepGrade: 'ਕੁਆਲਿਟੀ',
    stepPass: 'ਪਾਸ',
    stepCount: 'ਕਦਮ 2 / 4 ਚਾਲੂ',
    weighbridgeNo: 'ਨਿਰਧਾਰਿਤ ਕੰਡਾ',
    commodity: 'ਫ਼ਸਲ • Commodity',
    vehicleDetails: 'ਟਰੈਕਟਰ ਵੇਰਵਾ',
    totalApproved: 'ਕੁੱਲ ਮਨਜ਼ੂਰਸ਼ੁਦਾ ਰਕਮ',
    needCashUrgently: 'ਪੈਸੇ ਦੀ ਤੁਰੰਤ ਲੋੜ ਹੈ?',
    getAdvanceNow: '⚡ 80% ਪੈਸੇ ਤੁਰੰਤ ਲਵੋ',
    advanceSubtext: '2 ਮਿੰਟਾਂ ਵਿੱਚ ਖਾਤੇ ਵਿੱਚ ਪ੍ਰਾਪਤ ਕਰੋ। ਬਾਕੀ 20% ਬਾਅਦ ਵਿੱਚ ਮਿਲੇਗਾ।',
    linkedBank: 'ਲਿੰਕ ਕੀਤਾ ਬੈਂਕ ਖਾਤਾ',
    verified: 'ਤਸਦੀਕਸ਼ੁਦਾ',
    mandiTaxFree: 'ਸਰਕਾਰੀ ਮੰਡੀ ਫੀਸ: ₹0 (ਛੋਟ)',
    zeroInterest: 'ਐਡਵਾਂਸ ਫੀਸ: 0% ਵਿਆਜ ਮੁਕਤ',
    helpline: 'ਹੈਲਪਲਾਈਨ: 1800-180-1551 (ਟੋਲ ਫ੍ਰੀ)',
    portalTitle: 'ਕਿਸਾਨ ਮੰਡੀ ਈ-ਖ਼ਰੀਦ ਪੋਰਟਲ • ਏ.ਪੀ.ਐਮ.ਸੀ ਕੋਟਾ',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ ਭਲਾਈ ਮੰਤਰਾਲਾ | Ministry of Agriculture',
    nationalNetwork: 'ਰਾਸ਼ਟਰੀ ਖੇਤੀਬਾੜੀ ਮੰਡੀ (e-NAM) ਨੈੱਟਵਰਕ',
    tollFree: 'ਟੋਲ-ਫ੍ਰੀ ਹੈਲਪਲਾਈਨ',
    dashboardOverview: 'ਡੈਸ਼ਬੋਰਡ / Overview',
    liveYardQueue: 'ਲਾਈਵ ਕਤਾਰ / Live Queue',
    scheduleRates: 'ਮੰਡੀ ਕੈਲੰਡਰ ਤੇ MSP / Schedule',
    payoutsPassbook: 'ਭੁਗਤਾਨ ਤੇ ਪਾਸਬੁੱਕ / Payouts',
    enamMarket: 'e-NAM ਨਿਲਾਮੀ / Trade Slips',
    creditPassbook: 'ਕ੍ਰੈਡਿਟ ਪਾਸਬੁੱਕ / Passbook',
    staffControlDesk: 'ਸਟਾਫ਼ ਡੈਸਕ / Staff Desk',
    dailyIntake: 'ਕੁੱਲ ਆਮਦ (Daily Intake)',
    yourTokenStatus: 'ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ',
    approvedDbt: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ DBT ਭੁਗਤਾਨ',
    switchToMobile: 'ਮੋਬਾਈਲ ਵਿਊ (PWA)',
    switchToDesktop: 'ਡੈਸਕਟਾਪ ਪੋਰਟਲ',
    printPass: 'ਪਾਸ ਪ੍ਰਿੰਟ ਕਰੋ',
    getQrPass: 'QR ਪਾਸ ਦੇਖੋ',
    searchPlaceholder: 'ਖੋਜੋ: ਟੋਕਨ ਨੰ., ਗੱਡੀ ਨੰ. (RJ-20-EA-4412)...',
    chips: [
      'ਮੇਰੀ ਫ਼ਸਲ ਕਦੋਂ ਤੁਲੇਗੀ?',
      'ਅੱਜ ਕਣਕ ਦਾ ਕੀ ਭਾਅ ਹੈ?',
      'ਗੱਡੀ RJ-20-EA-4412 ਸਥਿਤੀ',
      '80% ਐਡਵਾਂਸ ਕਿਵੇਂ ਮਿਲੇਗਾ?'
    ]
  },
  mr: {
    appTitle: 'किसान मंडी',
    home: 'मुख्य',
    schedule: 'वेळापत्रक',
    queue: 'टोकन / रांग',
    payment: 'पेमेंट',
    staffDesk: 'स्टाफ डेस्क',
    speak: 'बोला',
    talkToSathi: 'साथी AI • बोला',
    sathiAssistant: 'साथी AI सहाय्यक',
    liveMandiData: 'थेट बाजार माहिती',
    greeting: 'राम लाल जी, नमस्कार! 🙏 मी तुमचा साथी AI सहाय्यक आहे. आज कोटा बाजारात गव्हाचा दर ₹2,275/क्विंटल आहे. तुमचा टोकन #42 आहे. आपण काहीही विचारू शकता.',
    listening: 'ऐकत आहे... कृपया बोला',
    askOrType: 'प्रश्न लिहा किंवा बोला...',
    send: 'विचारा',
    stop: 'थांबवा',
    listen: 'ऐका',
    selectLanguage: 'भाषा निवडा • Select Language',
    todayOpen: 'आज सुरू आहे',
    openToday: 'OPEN TODAY',
    gateOpen: 'गेट उघडे आहे',
    gateClosed: 'गेट बंद आहे',
    wheatProcurement: 'गहू खरेदी सुरू',
    govtMsp: 'शासकीय हमीभाव (MSP)',
    bookSlot: 'स्लॉट बुक करा',
    bookSlotSubtitle: 'रांगेत उभे राहू नका, वेळेवर पोहोचा',
    loadSize: 'वाहन व वजन',
    blockTokenNow: '🔒 टोकन त्वरित आरक्षित करा',
    blockTokenSub: '15 मिनिटांसाठी राखीव • गेट पास',
    showQrPass: 'सुरक्षा रक्षकाला QR पास दाखवा',
    mandiSteps: 'बाजार प्रक्रिया टप्पे',
    stepArrived: 'आले',
    stepWeighing: 'वजन',
    stepGrade: 'गुणवत्ता',
    stepPass: 'पास',
    stepCount: 'टप्पा 2 / 4 सुरू',
    weighbridgeNo: 'काटा क्रमांक',
    commodity: 'पीक • Commodity',
    vehicleDetails: 'ट्रॅक्टर तपशील',
    totalApproved: 'एकूण मंजूर रक्कम',
    needCashUrgently: 'त्वरित पैशांची गरज आहे?',
    getAdvanceNow: '⚡ त्वरित 80% पैसे मिळवा',
    advanceSubtext: '2 मिनिटांत बँक खात्यात मिळवा. उर्वरित 20% नियमित प्रक्रियेने मिळेल.',
    linkedBank: 'जोडलेले बँक खाते',
    verified: 'सत्यापित',
    mandiTaxFree: 'शासकीय बाजार शुल्क: ₹0 (सूट)',
    zeroInterest: 'अ‍ॅडव्हान्स शुल्क: 0% व्याज (सरकारी योजना)',
    helpline: 'हेल्पलाइन: 1800-180-1551 (टोल फ्री)',
    portalTitle: 'किसान मंडी ई-खरेदी पोर्टल • APMC कोटा',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'कृषी आणि शेतकरी कल्याण मंत्रालय | Ministry of Agriculture',
    nationalNetwork: 'राष्ट्रीय कृषी बाजार (e-NAM) नेटवर्क',
    tollFree: 'टोल-फ्री हेल्पलाइन',
    dashboardOverview: 'डॅशबोर्ड / Overview',
    liveYardQueue: 'थेट रांग / Live Queue',
    scheduleRates: 'बाजार वेळापत्रक व MSP',
    payoutsPassbook: 'पेमेंट व पासबुक / Payouts',
    enamMarket: 'e-NAM लिलाव / Trade Slips',
    creditPassbook: 'क्रेडिट पासबुक / Passbook',
    staffControlDesk: 'स्टाफ डेस्क / Staff Desk',
    dailyIntake: 'एकूण आवक (Daily Intake)',
    yourTokenStatus: 'तुमचा टोकन क्रमांक',
    approvedDbt: 'मंजूर DBT पेमेंट',
    switchToMobile: 'मोबाइल व्ह्यू (PWA)',
    switchToDesktop: 'डेस्कटॉप पोर्टल',
    printPass: 'पास प्रिंट करा',
    getQrPass: 'QR पास पहा',
    searchPlaceholder: 'शोधा: टोकन क्र., वाहन क्र. (RJ-20-EA-4412)...',
    chips: [
      'माझे पीक कधी मोजले जाईल?',
      'आज गव्हाचा भाव काय आहे?',
      'गाडी RJ-20-EA-4412 स्थिती',
      '80% अ‍ॅडव्हान्स कसा मिळेल?'
    ]
  },
  gu: {
    appTitle: 'કિસાન મંડી',
    home: 'મુખ્ય',
    schedule: 'તારીખ',
    queue: 'ટોકન / લાઈન',
    payment: 'ચુકવણી',
    staffDesk: 'સ્ટાફ ડેસ્ક',
    speak: 'બોલો',
    talkToSathi: 'સાથી AI • બોલો',
    sathiAssistant: 'સાથી AI સહાયક',
    liveMandiData: 'લાઈવ મંડી ડેટા',
    greeting: 'રામ લાલ જી, નમસ્તે! 🙏 હું તમારો સાથી AI સહાયક છું. આજે કોટા મંડીમાં ઘઉંનો ભાવ ₹2,275/ક્વિન્ટલ છે. તમારો ટોકન #42 છે. તમે બોલીને અથવા લખીને પૂછી શકો છો.',
    listening: 'સાંભળી રહ્યો છું... કૃપા કરીને બોલો',
    askOrType: 'પ્રશ્ન લખો અથવા બોલો...',
    send: 'પૂછો',
    stop: 'રોકો',
    listen: 'સાંભળો',
    selectLanguage: 'ભાષા પસંદ કરો • Select Language',
    todayOpen: 'આજે ખુલ્લું છે',
    openToday: 'OPEN TODAY',
    gateOpen: 'ગેટ ખુલ્લો છે',
    gateClosed: 'ગેટ બંધ છે',
    wheatProcurement: 'ઘઉંની ખરીદી ચાલુ',
    govtMsp: 'સરકારી ટેકાના ભાવ (MSP)',
    bookSlot: 'સ્લોટ બુક કરો',
    bookSlotSubtitle: 'લાઈન ટાળો, સમયસર પહોંચો',
    loadSize: 'વાહન અને જથ્થો',
    blockTokenNow: '🔒 ટોકન હમણાં જ બ્લોક કરો',
    blockTokenSub: '15 મિનિટ માટે અનામત • ગેટ પાસ',
    showQrPass: 'સુરક્ષા ગાર્ડને QR પાસ બતાવો',
    mandiSteps: 'મંડી પ્રક્રિયા પગલાં',
    stepArrived: 'પહોંચ્યા',
    stepWeighing: 'તોલ',
    stepGrade: 'ગુણવત્તા',
    stepPass: 'પાસ',
    stepCount: 'પગલું 2 / 4 ચાલુ',
    weighbridgeNo: 'નિયુક્ત કાંટો',
    commodity: 'પાક • Commodity',
    vehicleDetails: 'ટ્રેક્ટર વિગતો',
    totalApproved: 'કુલ મંજૂર રકમ',
    needCashUrgently: 'ત્વરિત પૈસાની જરૂર છે?',
    getAdvanceNow: '⚡ 80% પૈસા તરત મેળવો',
    advanceSubtext: '2 મિનિટમાં તમારા ખાતામાં મેળવો. બાકીના 20% સામાન્ય રીતે મળશે.',
    linkedBank: 'જોડાયેલ બેંક ખાતું',
    verified: 'ચકાસાયેલ',
    mandiTaxFree: 'સરકારી મંડી ફી: ₹0 (ખેડૂત છૂટ)',
    zeroInterest: 'એડવાન્સ ફી: 0% વ્યાજ (સરકારી યોજના)',
    helpline: 'હેલ્પલાઇન: 1800-180-1551 (ટોલ ફ્રી)',
    portalTitle: 'કિસાન મંડી ઈ-ખરીદી પોર્ટલ • APMC કોટા',
    portalSub: 'Digital Procurement Platform • Rajasthan Mandi Yard',
    ministryBar: 'કૃષિ અને ખેડૂત કલ્યાણ મંત્રાલય | Ministry of Agriculture',
    nationalNetwork: 'રાષ્ટ્રીય કૃષિ બજાર (e-NAM) નેટવર્ક',
    tollFree: 'ટોલ-ફ્રી હેલ્પલાઇન',
    dashboardOverview: 'ડેશબોર્ડ / Overview',
    liveYardQueue: 'લાઈવ લાઈન / Live Queue',
    scheduleRates: 'મંડી કેલેન્ડર અને MSP',
    payoutsPassbook: 'ચુકવણી અને પાસબુક / Payouts',
    enamMarket: 'e-NAM હરાજી / Trade Slips',
    creditPassbook: 'ક્રેડિટ પાસબુક / Passbook',
    staffControlDesk: 'સ્ટાફ ડેસ્ક / Staff Desk',
    dailyIntake: 'કુલ આવક (Daily Intake)',
    yourTokenStatus: 'તમારો ટોકન નંબર',
    approvedDbt: 'મંજૂર થયેલ DBT ચુકવણી',
    switchToMobile: 'મોબાઇલ વ્યૂ (PWA)',
    switchToDesktop: 'ડેસ્કટોપ પોર્ટલ',
    printPass: 'પાસ પ્રિન્ટ કરો',
    getQrPass: 'QR પાસ જુઓ',
    searchPlaceholder: 'શોધો: ટોકન નં., વાહન નં. (RJ-20-EA-4412)...',
    chips: [
      'મારો પાક ક્યારે તોલાશે?',
      'આજે ઘઉંનો ભાવ શું છે?',
      'વાહન RJ-20-EA-4412 સ્થિતિ',
      '80% એડવાન્સ કેવી રીતે મળશે?'
    ]
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('kisan_mandi_language') || 'hi';
  });

  const [isLangModalOpen, setIsLangModalOpen] = useState(false);

  const changeLanguage = (langCode) => {
    if (TRANSLATIONS[langCode]) {
      setCurrentLang(langCode);
      localStorage.setItem('kisan_mandi_language', langCode);
      setIsLangModalOpen(false);
    }
  };

  const currentLangObj = LANGUAGES.find((l) => l.code === currentLang) || LANGUAGES[0];

  const t = (key, fallback = '') => {
    const dict = TRANSLATIONS[currentLang] || TRANSLATIONS.hi;
    return dict[key] !== undefined ? dict[key] : fallback || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLang,
        currentLangObj,
        changeLanguage,
        isLangModalOpen,
        setIsLangModalOpen,
        t,
        LANGUAGES,
        speechCode: currentLangObj.speechCode
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}
